### ISSUE TITLE
Use of usize in tutorial instead of u64

### ISSUE THREAD

**Issue by mdtro** [distrentic/plum#4]
[In your blog write-up](https://onatm.dev/2020/08/10/let-s-implement-a-bloom-filter/) the function for `bitmap_size()` is:

```rust
    fn bitmap_size(items_count: usize, fp_rate: f64) -> usize {
        let ln2_2 = core::f64::consts::LN_2 * core::f64::consts::LN_2;
        ((-1.0f64 * items_count as f64 * fp_rate.ln()) / ln2_2).ceil() as usize
    }
```

This should match what you have in `lib.rs` with the return types as `u64` and not `usize`.

Thank you for the blog post! I enjoyed reading and working through it!

**Comment by onatm** [comment]
Hey @mdtro thank you for reporting this and I am very happy that you enjoyed reading the blog post!

@idursun wanna have a look?
